name: prem-automation.yml
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0,12 * * 5,6,0,1'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create google credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: | 
          mkdir -p src/main/resources 
          echo "$GOOGLE_CREDENTIALS" > src/main/resources/credentials.json

      - name: Run application
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SPREAD_SHEET_ID: ${{ secrets.SPREAD_SHEET_ID }}
        run: mvn clean compile exec:java

